
logLevel = "debug"

[fetcher]
timeout = 3000
proxy = ["http://127.0.0.1:8888", "http://127.0.0.1:8888"]

[storage]
sqlURL = "root:123456@tcp(127.0.0.1:3326)/crawler?charset=utf8"

[GRPCServer]
HTTPListenAddress = ":8080"
GRPCListenAddress = ":9090"
ID = "1"
RegistryAddress = ":2379"
RegisterTTL = 60
RegisterInterval = 15
ClientTimeOut   = 10
Name = "go.micro.server.worker"

[TaskList]
Tasks = [
    {Name = "douban_book_list"},
    {Name = "find_douban_sun_room"}
]